name: voces

recipe: laravel
config:
  webroot: public
  php: '8.5'
  database: mysql

services:
  appserver:
    build_as_root:
      - curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
      - apt-get install -y nodejs
  mailhog:
    type: mailhog
    portforward: false

proxy:
  appserver:
    - voces.lndo.site
    - widget.voces.lndo.site:5173
  mailhog:
    - mailhog.voces.lndo.site
