name: voces

recipe: laravel
config:
  webroot: public
  php: "8.5"
  database: mysql

services:
  mailhog:
    type: mailhog
    portforward: false

proxy:
  appserver:
    - voces.lndo.site
  mailhog:
    - mailhog.voces.lndo.site
