name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  # ------------------------------------
  # 1. PRODUCTION DEPLOYMENT
  # ------------------------------------
  deploy-production:
    runs-on: [self-hosted, prod]
    steps:
      - name: Execute Prod Deployment
        run: |
          cd /home/voces-app/htdocs/app.voces.ch
          ./deploy.sh

  # ------------------------------------
  # 2. DEMO DEPLOYMENT
  # ------------------------------------
  deploy-demo:
    runs-on: [self-hosted, demo]
    steps:
      - name: Execute Demo Deployment
        run: |
          cd /home/voces-demo/htdocs/demo.voces.ch
          ./deploy.sh
