name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, deploy]

    steps:
      - name: Execute Deployment Script
        run: |
          cd /home/voces-app/htdocs/app.voces.ch
          ./deploy.sh
